version: '3.6'
services:
  base:
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - '.:/app'
    ports:
      - 5002:5000
    environment:
      - FLASK_APP=project/__init__.py
      - FLASK_ENV=production
      - APP_SETTINGS=project.config.ProductionConfig